name: 'Run Municipio Smoke Tests'
description: 'A custom action to run Municipio Smoke tests'
inputs:
  sitemap-urls:
    description: 'A comma-separated list of URLs to test'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        repository: helsingborg-stad/municipio-smoke-tests
        token: ${{ github.token }}
        ref: 'v1'

    - name: Cache Composer dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Setup PHP with composer v2.
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --no-interaction
      shell: bash

    - name: Setup shard files
      run: |
        php src/prepare.php
      shell: bash
      env:
        SITEMAP_URLS: ${{ inputs.sitemap-urls }}